# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_view', models.ImageField(upload_to='gallery/')),
                ('image_description', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
