# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Project',
        ),
    ]
