# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
