# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190320_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
